# Generated by Django 3.2.9 on 2022-05-01 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post2',
        ),
    ]
