# Generated by Django 3.2.9 on 2022-05-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_delete_post2'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', '下書き'), ('public', '公開')], default='draft', max_length=8, verbose_name='公開ステータス'),
        ),
    ]
