# Generated by Django 3.2.9 on 2022-05-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(choices=[('jiro', 'Jiro')], default='jiro', max_length=10, verbose_name='著者'),
        ),
    ]
